export interface Question {
  id: number
  category: string
  content: string
  ttsText?: string
  starter?: string
}

const P = '자, 천천히 편하게 말씀하세요. '

export const QUESTIONS: Question[] = [
  { id: 1,  category: '출생·고향',   content: '태어난 곳은 어디인가요?',                                   ttsText: P + '태어난 곳은 어디인가요?',                                   starter: '내가 태어난 곳 이야기를 하자면...' },
  { id: 2,  category: '출생·고향',   content: '자라난 동네 이름과 그곳의 기억을 이야기해 주세요.',           ttsText: P + '자라난 동네 이름과 그곳의 기억을 이야기해 주세요.',           starter: '내가 자라난 동네를 떠올리면...' },
  { id: 3,  category: '출생·고향',   content: '어린 시절 살던 집을 묘사해 주세요.',                         ttsText: P + '어린 시절 살던 집을 묘사해 주세요.',                         starter: '어린 시절 내가 살던 집은...' },
  { id: 4,  category: '출생·고향',   content: '고향에서 가장 좋아하던 장소는 어디인가요?',                   ttsText: P + '고향에서 가장 좋아하던 장소는 어디인가요?',                   starter: '고향에서 내가 가장 좋아했던 곳은...' },
  { id: 5,  category: '출생·고향',   content: '어린 시절 집 근처에 어떤 가게나 장소가 있었나요?',            ttsText: P + '어린 시절 집 근처에 어떤 가게나 장소가 있었나요?',            starter: '어릴 때 우리 집 근처에는...' },
  { id: 6,  category: '출생·고향',   content: '고향의 계절 풍경 중 가장 기억에 남는 것은?',                  ttsText: P + '고향의 계절 풍경 중 가장 기억에 남는 것은?',                  starter: '고향의 계절 풍경 중 가장 기억나는 건...' },
  { id: 7,  category: '출생·고향',   content: '고향 사투리나 독특한 표현이 있었나요?',                       ttsText: P + '고향 사투리나 독특한 표현이 있었나요?',                       starter: '고향에서 쓰던 말 중에 기억나는 건...' },
  { id: 8,  category: '출생·고향',   content: '처음으로 고향을 떠났을 때의 기억은?',                         ttsText: P + '처음으로 고향을 떠났을 때의 기억은?',                         starter: '처음 고향을 떠나던 날을 생각하면...' },
  { id: 9,  category: '학창시절',    content: '다니던 초등학교 이름은 무엇인가요?',                          ttsText: P + '다니던 초등학교 이름은 무엇인가요?',                          starter: '내가 다니던 초등학교를 이야기하자면...' },
  { id: 10, category: '학창시절',    content: '가장 좋아했던 선생님은 누구였나요?',                          ttsText: P + '가장 좋아했던 선생님은 누구였나요?',                          starter: '내가 가장 좋아했던 선생님을 떠올리면...' },
  { id: 11, category: '학창시절',    content: '학창시절 가장 친했던 친구 이름은?',                           ttsText: P + '학창시절 가장 친했던 친구 이름은?',                           starter: '학창 시절 내 가장 친한 친구를 생각하면...' },
  { id: 12, category: '학창시절',    content: '학교에서 가장 잘했던 과목은 무엇인가요?',                      ttsText: P + '학교에서 가장 잘했던 과목은 무엇인가요?',                      starter: '학교에서 내가 가장 잘했던 과목은...' },
  { id: 13, category: '학창시절',    content: '학교 운동회나 소풍에서의 특별한 기억은?',                      ttsText: P + '학교 운동회나 소풍에서의 특별한 기억은?',                      starter: '운동회나 소풍 기억을 떠올리면...' },
  { id: 14, category: '학창시절',    content: '중학교 또는 고등학교 때 열심히 했던 것은?',                    ttsText: P + '중학교 또는 고등학교 때 열심히 했던 것은?',                    starter: '중고등학교 시절 내가 열심히 했던 건...' },
  { id: 15, category: '학창시절',    content: '학창시절 받은 선물 중 가장 기억에 남는 것은?',                 ttsText: P + '학창시절 받은 선물 중 가장 기억에 남는 것은?',                 starter: '학창 시절 받은 선물 중 가장 기억나는 건...' },
  { id: 16, category: '학창시절',    content: '졸업식 날의 기억을 이야기해 주세요.',                          ttsText: P + '졸업식 날의 기억을 이야기해 주세요.',                          starter: '졸업식 날을 생각하면...' },
  { id: 17, category: '학창시절',    content: '학교 시험이나 발표에서 기억에 남는 순간은?',                   ttsText: P + '학교 시험이나 발표에서 기억에 남는 순간은?',                   starter: '시험이나 발표 중에 기억나는 순간을 이야기하자면...' },
  { id: 18, category: '가족·부모님', content: '어머니의 목소리나 말투가 기억나시나요?',                       ttsText: P + '어머니의 목소리나 말투가 기억나시나요?',                       starter: '어머니의 목소리를 떠올리면...' },
  { id: 19, category: '가족·부모님', content: '아버지에 대한 가장 오래된 기억은?',                            ttsText: P + '아버지에 대한 가장 오래된 기억은?',                            starter: '아버지에 대한 기억을 떠올리면...' },
  { id: 20, category: '가족·부모님', content: '형제자매는 몇 명이고 각자 어떤 사람이었나요?',                  ttsText: P + '형제자매는 몇 명이고 각자 어떤 사람이었나요?',                  starter: '내 형제자매 이야기를 하자면...' },
  { id: 21, category: '가족·부모님', content: '명절에 온 가족이 모여 하던 일은?',                             ttsText: P + '명절에 온 가족이 모여 하던 일은?',                             starter: '명절에 온 가족이 모이면...' },
  { id: 22, category: '가족·부모님', content: '부모님께 가장 혼났던 기억이 있다면?',                          ttsText: P + '부모님께 가장 혼났던 기억이 있다면?',                          starter: '부모님께 크게 혼났던 기억을 이야기하자면...' },
  { id: 23, category: '가족·부모님', content: '부모님이 자주 하시던 말씀이나 가르침은?',                       ttsText: P + '부모님이 자주 하시던 말씀이나 가르침은?',                       starter: '부모님이 자주 하시던 말씀을 생각하면...' },
  { id: 24, category: '가족·부모님', content: '어린 시절 가족이 함께한 가장 즐거운 기억은?',                   ttsText: P + '어린 시절 가족이 함께한 가장 즐거운 기억은?',                   starter: '가족이 함께 즐겁게 지냈던 기억을 이야기하자면...' },
  { id: 25, category: '가족·부모님', content: '형제자매와 함께했던 장난이나 추억은?',                          ttsText: P + '형제자매와 함께했던 장난이나 추억은?',                          starter: '형제자매와 함께했던 추억을 떠올리면...' },
  { id: 26, category: '가족·부모님', content: '할머니나 할아버지와의 기억이 있다면?',                          ttsText: P + '할머니나 할아버지와의 기억이 있다면?',                          starter: '할머니, 할아버지와의 기억을 생각하면...' },
  { id: 27, category: '음식·추억',   content: '어린 시절 가장 좋아하던 음식은 무엇이었나요?',                  ttsText: P + '어린 시절 가장 좋아하던 음식은 무엇이었나요?',                  starter: '어릴 때 내가 가장 좋아하던 음식은...' },
  { id: 28, category: '음식·추억',   content: '어머니가 해주시던 음식 중 가장 그리운 것은?',                   ttsText: P + '어머니가 해주시던 음식 중 가장 그리운 것은?',                   starter: '어머니가 해주시던 음식 중 가장 그리운 건...' },
  { id: 29, category: '음식·추억',   content: '어릴 때 즐겨 부르던 노래나 동요는?',                           ttsText: P + '어릴 때 즐겨 부르던 노래나 동요는?',                           starter: '어릴 때 즐겨 부르던 노래를 떠올리면...' },
  { id: 30, category: '음식·추억',   content: '어린 시절 즐겨 하던 놀이는 무엇인가요?',                        ttsText: P + '어린 시절 즐겨 하던 놀이는 무엇인가요?',                        starter: '어릴 때 내가 즐겨 하던 놀이는...' },
  { id: 31, category: '음식·추억',   content: '처음으로 먹어본 특별한 음식의 기억은?',                         ttsText: P + '처음으로 먹어본 특별한 음식의 기억은?',                         starter: '처음 먹어봤던 특별한 음식을 생각하면...' },
  { id: 32, category: '음식·추억',   content: '가장 기억에 남는 생일잔치는 언제였나요?',                       ttsText: P + '가장 기억에 남는 생일잔치는 언제였나요?',                       starter: '기억에 남는 생일잔치를 떠올리면...' },
  { id: 33, category: '음식·추억',   content: '어릴 때 즐겨 읽던 책이나 만화가 있었나요?',                     ttsText: P + '어릴 때 즐겨 읽던 책이나 만화가 있었나요?',                     starter: '어릴 때 즐겨 읽던 책이나 만화를 생각하면...' },
  { id: 34, category: '음식·추억',   content: '어린 시절 가장 갖고 싶었던 물건은?',                           ttsText: P + '어린 시절 가장 갖고 싶었던 물건은?',                           starter: '어릴 때 내가 가장 갖고 싶었던 건...' },
  { id: 35, category: '음식·추억',   content: '어릴 때 즐겨 보던 TV 프로그램이나 영화는?',                     ttsText: P + '어릴 때 즐겨 보던 TV 프로그램이나 영화는?',                     starter: '어릴 때 즐겨 보던 TV 프로그램을 생각하면...' },
  { id: 36, category: '결혼·가정',   content: '배우자를 처음 만난 날을 기억하시나요?',                         ttsText: P + '배우자를 처음 만난 날을 기억하시나요?',                         starter: '지금의 배우자를 처음 만났을 때...' },
  { id: 37, category: '결혼·가정',   content: '결혼식 날의 기억을 이야기해 주세요.',                           ttsText: P + '결혼식 날의 기억을 이야기해 주세요.',                           starter: '결혼식 날을 생각하면...' },
  { id: 38, category: '결혼·가정',   content: '자녀 중 첫째가 태어난 날 기억나시나요?',                        ttsText: P + '자녀 중 첫째가 태어난 날 기억나시나요?',                        starter: '첫째 아이가 태어나던 날을 생각하면...' },
  { id: 39, category: '결혼·가정',   content: '가족과 함께한 가장 행복한 여행은?',                             ttsText: P + '가족과 함께한 가장 행복한 여행은?',                             starter: '가족과 함께한 여행 중에서 가장 기억나는 건...' },
  { id: 40, category: '결혼·가정',   content: '결혼 후 처음 살던 집의 기억은?',                               ttsText: P + '결혼 후 처음 살던 집의 기억은?',                               starter: '결혼 후 처음 살던 집을 생각하면...' },
  { id: 41, category: '결혼·가정',   content: '자녀를 키우면서 가장 뿌듯했던 순간은?',                         ttsText: P + '자녀를 키우면서 가장 뿌듯했던 순간은?',                         starter: '아이들을 키우면서 가장 뿌듯했던 순간을 이야기하자면...' },
  { id: 42, category: '결혼·가정',   content: '가족과 함께 매년 챙기던 행사나 전통이 있었나요?',                ttsText: P + '가족과 함께 매년 챙기던 행사나 전통이 있었나요?',                starter: '우리 가족만의 전통을 이야기하자면...' },
  { id: 43, category: '결혼·가정',   content: '배우자에게 가장 고마운 일은 무엇인가요?',                        ttsText: P + '배우자에게 가장 고마운 일은 무엇인가요?',                        starter: '배우자에게 가장 감사한 건...' },
  { id: 44, category: '결혼·가정',   content: '자녀에게 꼭 전하고 싶은 이야기가 있다면?',                       ttsText: P + '자녀에게 꼭 전하고 싶은 이야기가 있다면?',                       starter: '자녀에게 꼭 전하고 싶은 말이 있다면...' },
  { id: 45, category: '직업·성취',   content: '첫 직장은 어디였고 어떤 일을 했나요?',                          ttsText: P + '첫 직장은 어디였고 어떤 일을 했나요?',                          starter: '내 첫 직장 이야기를 하자면...' },
  { id: 46, category: '직업·성취',   content: '가장 자랑스러운 성취를 꼽는다면?',                              ttsText: P + '가장 자랑스러운 성취를 꼽는다면?',                              starter: '내 삶에서 가장 자랑스러운 성취는...' },
  { id: 47, category: '직업·성취',   content: '일하면서 가장 힘들었던 순간은 언제였나요?',                      ttsText: P + '일하면서 가장 힘들었던 순간은 언제였나요?',                      starter: '일하면서 가장 힘들었던 때를 생각하면...' },
  { id: 48, category: '직업·성취',   content: '직장에서 가장 오래 기억에 남는 동료는?',                         ttsText: P + '직장에서 가장 오래 기억에 남는 동료는?',                         starter: '직장 동료 중에 가장 기억에 남는 사람은...' },
  { id: 49, category: '직업·성취',   content: '일을 통해 배운 가장 중요한 것은 무엇인가요?',                    ttsText: P + '일을 통해 배운 가장 중요한 것은 무엇인가요?',                    starter: '일을 통해 배운 가장 중요한 것을 이야기하자면...' },
  { id: 50, category: '직업·성취',   content: '젊은 시절 꿈꾸던 직업은 무엇이었나요?',                         ttsText: P + '젊은 시절 꿈꾸던 직업은 무엇이었나요?',                         starter: '젊은 시절 내가 꿈꾸던 직업은...' },
  { id: 51, category: '직업·성취',   content: '평생 가장 보람을 느꼈던 일은 무엇인가요?',                       ttsText: P + '평생 가장 보람을 느꼈던 일은 무엇인가요?',                       starter: '평생 살면서 가장 보람을 느꼈던 건...' },
  { id: 52, category: '직업·성취',   content: '은퇴하던 날 또는 마지막 출근날의 기억은?',                       ttsText: P + '은퇴하던 날 또는 마지막 출근날의 기억은?',                       starter: '마지막 출근날을 생각하면...' },
  { id: 53, category: '인생·가치관', content: '살면서 가장 감사한 일은 무엇인가요?',                            ttsText: P + '살면서 가장 감사한 일은 무엇인가요?',                            starter: '살면서 가장 감사했던 일을 이야기하자면...' },
  { id: 54, category: '인생·가치관', content: '인생에서 가장 중요하게 여기는 것은?',                            ttsText: P + '인생에서 가장 중요하게 여기는 것은?',                            starter: '내 인생에서 가장 중요하게 여기는 건...' },
  { id: 55, category: '인생·가치관', content: '다시 산다면 어떤 일을 다르게 하고 싶나요?',                      ttsText: P + '다시 산다면 어떤 일을 다르게 하고 싶나요?',                      starter: '다시 살 수 있다면 나는...' },
  { id: 56, category: '인생·가치관', content: '지금의 나에게 가장 큰 영향을 준 사람은?',                        ttsText: P + '지금의 나에게 가장 큰 영향을 준 사람은?',                        starter: '지금의 내게 가장 큰 영향을 준 사람은...' },
  { id: 57, category: '인생·가치관', content: '인생에서 가장 힘든 고비는 어떻게 넘겼나요?',                     ttsText: P + '인생에서 가장 힘든 고비는 어떻게 넘겼나요?',                     starter: '가장 힘들었던 시절을 돌이켜 보면...' },
  { id: 58, category: '인생·가치관', content: '살면서 가장 용감하게 한 행동은?',                               ttsText: P + '살면서 가장 용감하게 한 행동은?',                               starter: '내 인생에서 가장 용감하게 한 행동은...' },
  { id: 59, category: '인생·가치관', content: '젊은 세대에게 꼭 전하고 싶은 말이 있다면?',                      ttsText: P + '젊은 세대에게 꼭 전하고 싶은 말이 있다면?',                      starter: '젊은 세대에게 꼭 전하고 싶은 말이 있다면...' },
  { id: 60, category: '인생·가치관', content: '내 인생을 한 문장으로 표현한다면?',                              ttsText: P + '내 인생을 한 문장으로 표현한다면?',                              starter: '내 인생을 한 문장으로 표현하자면...' },
  { id: 61, category: '인생·가치관', content: '가장 행복했던 시절은 언제였나요?',                               ttsText: P + '가장 행복했던 시절은 언제였나요?',                               starter: '내 인생에서 가장 행복했던 때를 이야기하자면...' },
  { id: 62, category: '현재·일상',   content: '요즘 가장 즐거운 일은 무엇인가요?',                              ttsText: P + '요즘 가장 즐거운 일은 무엇인가요?',                              starter: '요즘 내가 가장 즐거운 일은...' },
  { id: 63, category: '현재·일상',   content: '요즘 즐겨 드시는 음식은 무엇인가요?',                            ttsText: P + '요즘 즐겨 드시는 음식은 무엇인가요?',                            starter: '요즘 내가 즐겨 먹는 음식은...' },
  { id: 64, category: '현재·일상',   content: '가장 자주 연락하는 사람은 누구인가요?',                          ttsText: P + '가장 자주 연락하는 사람은 누구인가요?',                          starter: '요즘 내가 가장 자주 연락하는 사람은...' },
  { id: 65, category: '현재·일상',   content: '요즘 자주 가는 장소가 있다면?',                                  ttsText: P + '요즘 자주 가는 장소가 있다면?',                                  starter: '요즘 내가 자주 가는 곳은...' },
  { id: 66, category: '현재·일상',   content: '요즘 관심을 갖고 있는 것은 무엇인가요?',                         ttsText: P + '요즘 관심을 갖고 있는 것은 무엇인가요?',                         starter: '요즘 내가 관심 갖고 있는 건...' },
  { id: 67, category: '현재·일상',   content: '하루 중 가장 좋아하는 시간대는?',                                ttsText: P + '하루 중 가장 좋아하는 시간대는?',                                starter: '하루 중 내가 가장 좋아하는 시간은...' },
  { id: 68, category: '현재·일상',   content: '지금 가장 보고 싶은 사람은 누구인가요?',                         ttsText: P + '지금 가장 보고 싶은 사람은 누구인가요?',                         starter: '지금 내가 가장 보고 싶은 사람은...' },
  { id: 69, category: '현재·일상',   content: '요즘 즐겨 듣는 음악이나 좋아하는 노래는?',                       ttsText: P + '요즘 즐겨 듣는 음악이나 좋아하는 노래는?',                       starter: '요즘 내가 즐겨 듣는 노래는...' },
  { id: 70, category: '현재·일상',   content: '오늘 아침 무엇을 먹었고 어떤 하루였나요?',                       ttsText: P + '오늘 아침 무엇을 먹었고 어떤 하루였나요?',                       starter: '오늘을 이야기하자면...' },
]

// DB voice_diary.questions serial: 70개 일반 문항 + 1개 자유(is_common=true) = id 71
export const FINAL_QUESTION: Question = {
  id: 71,
  category: '자유',
  content: '지금 남기고 싶은 이야기를 편하게 자유롭게 말해 주세요.',
  ttsText: P + '지금 남기고 싶은 이야기를 편하게 자유롭게 말해 주세요.',
  starter: '지금 이 순간 하고 싶은 이야기는...',
}
